spring.application.name=primal-might-demo-backend
spring.config.import=optional:classpath:application-local.properties

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.datasource.url=jdbc:mysql://localhost:3306/primal-might-demo?createDatabaseIfNotExist=true&serverTimezone=Europe/Moscow&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
